/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Celula;
import Modelo.Tejido;
import Modelo.Vertice;
import java.awt.FlowLayout;
import java.awt.Graphics;
import java.awt.Rectangle;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author JHONATAN
 */
public class GraficoBarras extends javax.swing.JFrame {

    private BufferedImage grafica = null;
    private Tejido<Celula> tejido = null;
    private ArrayList<String[]> listaResultados = null;
    /**
     * Creates new form GraficoBarras
     */
    public GraficoBarras(Tejido tejido) {
        super("Grafico Estadistico.");
        initComponents();
        this.tejido = tejido;
        setExtendedState(MAXIMIZED_BOTH);
        setVisible(true);       
    }

    public BufferedImage creaImagen() {
        DefaultCategoryDataset modelo = new DefaultCategoryDataset();
         // column keys...
        int[] numeroCelulas = new int[20];
        for(int i = 0; i < numeroCelulas.length; i++){
            numeroCelulas[i] = 0;
        }
        ArrayList<Vertice<Celula>> lista = tejido.getTejidoG().getLista_vertices();
        for(int i = 0; i < tejido.getTejidoG().getLista_vertices().size(); i++){
            numeroCelulas[lista.get(i).getInfo().getNumLado()]++;
            System.out.println(i+". "+lista.get(i).getInfo().getId()+" "+lista.get(i).getInfo().getNumLado());
        }
        
        listaResultados = new ArrayList<>();
        
        for(int i = 0; i < numeroCelulas.length; i++){
            if(numeroCelulas[i] != 0){
                String[] valores = new String[2];
                valores[0] = i+"";
                valores[1] = numeroCelulas[i]+"";
                listaResultados.add(valores);
                modelo.addValue(numeroCelulas[i], tejido.getNombre(), i + " lados");
            }
        }
        
        
        
        boolean legend = true;
        boolean tooltips = true;
        boolean urls = false;
        JFreeChart chart = ChartFactory.createBarChart(
                "Celulas por numero de lados",
                "Numero de Lados",
                "Cantidad de celulas",
                modelo,
                PlotOrientation.VERTICAL,
                legend,
                tooltips,
                urls);
        return chart.createBufferedImage(getSize().width-400, getSize().height-100);
    }

    public void paint(java.awt.Graphics g) {
        //super.paint(g);
        if (grafica == null) {
            grafica = this.creaImagen();
        }
        g.drawImage(grafica, 30, 30, null); 
        JLabel[] lbl = imprimirResultados();
            for(int i = 0; i < lbl.length; i++){
                g.drawString(lbl[i].getText(), 950, 200 + 20*i);
            }
    }
    
    public JLabel[] imprimirResultados(){
        JLabel[] lstLabel = new JLabel[listaResultados.size()];
        
        
        for(int i = 0; i < listaResultados.size(); i++){
            lstLabel[i] = new JLabel("Numero de celulas de "+listaResultados.get(i)[0] +" lados: "+listaResultados.get(i)[1]);
   
        }
        return lstLabel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
